import type { Metadata } from "next";
import "./globals.css";

//font
import { Roboto, Merriweather } from "next/font/google";

//components
import NavBar from "./components/navbar/nav-bar";

//font
//--primary
const merriweather = Merriweather({
  variable: "--font-merriweather-serif",
  weight: ["400", "500", "700"],
  subsets: ["latin"],
});
//--secondary
const roboto = Roboto({
  variable: "--font-roboto-sans",
  weight: ["400", "500", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${merriweather.variable} ${roboto.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <NavBar />
        {children}
      </body>
    </html>
  );
}
